# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 60  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster


arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 60  # Hz
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: cr5

    # Future time offset for trajectory prediction (in seconds)
    future_time_offset: 2.0

    # Control parameters
    home_1: [3.66519, 0.0, -1.5708, 0.0, 1.5708, 0.0]
    home_pos: [3.66519, 0.0, -1.5708, 0.0, 1.5708, 0.0]
    rest_pos: [3.66519, 0.0, -1.5708, 0.0, 1.5708, 0.0]

hand_controller:
  ros__parameters:
    joint: gripper_joint
    use_effort_interface: false

force_torque_sensor_broadcaster:
  ros__parameters:
    frame_id: "ft_sensor"
    sensor_name: "ft_sensor"
    sensor_filter_chain:
      filter1:
        name: gravity_compensation
        type: control_filters/GravityCompensationWrench
        params:
          world_frame: "base_link"
          sensor_frame: "ft_sensor"
          tool:
            CoG: [-0.01285, 0.00209, 0.14197]
            gravity_field: [0.0, 0.0, -9.81]
            mass: 0.4
      filter2:
        name: low_pass_filter
        type: control_filters/LowPassFilterWrench
        params:
          cutoff_frequency: 10.0
          damping_frequency: 10.0
          damping_intensity: 1.0
          sampling_frequency: 60.0
