# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 60  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController


arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 60  # Hz
    mpc_frequency: 30.0
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: cr5

    # Future time offset for trajectory prediction (in seconds)
    future_time_offset: 2.0

    # Control parameters
    home_pos: [3.83, 0.23, -2.14, 0.64, 1.31, 0.49]
    rest_pos: [3.14, 0.0, -1.57, 0.0, 1.57, 0.0]